config/routes.rb
Rails.application.routes.draw do
  root :to => 'oauth_test#index'
  get 'oauth_test/index'
  get 'relationships/create'
  get 'relationships/destroy'


  resources :blogs
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :favorites, only: [:create, :destroy, :index]
  resources :users, only: [:index]
  resources :relationships, only: [:create, :destroy]

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user


  scope :index_all, -> {
    select(:id, :title, :content, :created_at, :updated_at, :image, :user_id)
    .order(created_at: :asc)
    .includes(:user)
  }

  paginates_per 10

  mount_uploader :image, ImageUploader
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :blog
  belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :followed, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :blogs
  has_many :favorites, dependent: :destroy
  has_many :favorite_blogs, through: :favorites, source: :blog
  has_many :active_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :passive_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:omniauthable, omniauth_providers: %i(google facebook)

  def follow!(other_user)
    active_relationships.create!(followed_id: other_user.id)
  end

  def following?(other_user)
    active_relationships.find_by(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def self.create_unique_string
    SecureRandom.uuid
  end

  def self.find_for_google(auth)
    user = User.find_by(email: auth.info.email)

    unless user
      user = User.new(email: auth.info.email,
                      provider: auth.provider,
                      uid:      auth.uid,
                      password: Devise.friendly_token[0, 20],
                                 )
    end
    user.save
    user
  end

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
   user = User.find_by(provider: auth.provider, uid: auth.uid)

   unless user
     user = User.new(provider: auth.provider,
                     uid:      auth.uid,
                     email:    "#{auth.uid}-#{auth.provider}@example.com",
                     password: Devise.friendly_token[0, 20]
     )
   end
   user.save
   user
 end

  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image, :image_cache])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :image, :image_cache])
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only:[:new, :edit, :destroy]

  def index
    # @blogs = Blog.index_all.page(params[:page])
    @q = Blog.ransack(params[:q])
    @blogs = @q.result
  end

  def show
    @favorite = current_user.favorites.find_by(blog_id: @blog.id)
  end

  def new
    if params[:back]
      @blog = Blog.new(blog_params)
    else
      @blog = Blog.new
    end
  end

  def confirm
    @blog = current_user.blogs.build(blog_params)
    render:new if @blog.invalid?
  end

  def edit
  end

  def create
    @blog = current_user.blogs.build(blog_params)
    respond_to do |format|
      if @blog.save
        NoticeMailer.sendmail_blog(@blog).deliver
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :content, :image, :image_cache)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def index
    @favorites = current_user.favorite_blogs
  end

  def create
    favorite = current_user.favorites.create(blog_id: params[:blog_id])
    redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/oauth_test_controller.rb
class OauthTestController < ApplicationController
  def index
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!

  def create
    if user_signed_in?
     @user = User.find(params[:relationship][:followed_id])
     current_user.follow!(@user)
     @user
   else
     @user
   end
  end

  def destroy
   @user = Relationship.find(params[:id]).followed
   current_user.unfollow!(@user)
   @user
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google
    @user = User.find_for_google(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "google") if is_navigational_format?
    else
      session['devise.google_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

  def facebook
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def build_resource(hash={})
    hash[:uid] = User.create_unique_string
    super
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/oauth_test_helper.rb
module OauthTestHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_for(blog) do |f| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= image_tag(@blog.image.url) if @blog.image.url %>
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogs/confirm.html.erb
<h1>確認画面</h1>
<%= form_with(model: @blog, url: blogs_path, local: true) do |form| %>
  <%= image_tag(@blog.image.url) %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit "投稿する" %>
<% end %>

<%= form_with(model:@blog, url:new_blog_path, local:true, method:"get") do |form| %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit "戻る", name: "back" %>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<h1>Blogs</h1>

<%= search_form_for @q do |f| %>
  <%= f.label :title_cont %>
  <%= f.search_field :title_cont %>
  <%= f.submit %>
<% end %>

<table>
  <thead>
    <tr>
      <th><%= sort_link(@q, :user_name) %></th>
      <th>title</th>
      <th>content</th>
    </tr>
  </thead>
  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.user.name %></td>
        <td><%= blog.title %></td>
        <td><%= blog.content %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @blog.content %>
</p>

<p>
  <% if @blog.image.present? %>
    <strong>Image:</strong>
    <%= image_tag @blog.image.url %>
   <% end %>
</p>

<% unless @blog.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(blog_id: @blog.id), method: :post %>
  <% end %>
<% end %>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/favorites/index.html.erb
<h1>Favorites</h1>

<table>
  <thead>
    <tr>
      <th>User_name</th>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @favorites.each do |favorite| %>
      <tr>
        <td><%= favorite.user.name %></td>
        <td><%= favorite.title %></td>
        <td><%= favorite.content %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Blog index', blogs_path %>

app/views/relationships/create.html.erb
<h1>Relationships#create</h1>
<p>Find me in app/views/relationships/create.html.erb</p>

app/views/relationships/create.js.erb
$("#follow_form_"+"<%= @user.id %>").html("<%= escape_javascript(render partial: 'users/follow_form', locals: { user: @user } ) %>")

app/views/relationships/destroy.html.erb
<h1>Relationships#destroy</h1>
<p>Find me in app/views/relationships/destroy.html.erb</p>

app/views/relationships/destroy.js.erb
$("#follow_form_"+"<%= @user.id %>").html("<%= escape_javascript(render partial: 'users/follow_form', locals: { user: @user } ) %>")

app/views/users/_follow_form.html.erb
<div id="follow_form_<%= user.id %>">
  <% unless current_user.following?(user) %>
    <%= form_with(model: current_user.active_relationships.build(followed_id: user.id)) do |f| %>
      <%= f.hidden_field :followed_id %>
      <%= f.submit "フォロー" %>
    <% end %>
  <% else %>
    <%= form_with(model: current_user.active_relationships.find_by(followed_id: user.id), method: :delete ) do |f| %>
      <%= f.submit "つながりを解除" %>
    <% end %>
  <% end %>
</div>

app/views/users/index.html.erb
<h2>ユーザー</h2>
<% @users.each do |user| %>
  <%= user.name %>
  <%= user.email %>
  <%= render 'follow_form', user: user %>
<% end %>